config/routes.rb
Rails.application.routes.draw do
  
	root 'home#index'
  resources :orders, only: [:create, :update, :show] do
  	get 'summary' => 'orders#summary'
  end

	resources :customers, only: [:new, :create]
	resources :confirmations, only: [:new, :create, :update]
	get 'deliveries/login' => 'deliveries#login', as: 'login_deliveries'
  get 'deliveries' => redirect('deliveries/login', status: 301)
  resources :deliveries, only: [:create, :show, :destroy] do
  	get 'orders' => 'deliveries#orders'
  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :orders
end

app/models/confirmation.rb
class Confirmation < ActiveRecord::Base
	require 'securerandom'
	belongs_to :customer
	belongs_to :order

	validates :phone_number, presence: true

	def self.one_time_password
		SecureRandom.hex(4)
	end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :confirmations
	has_many :orders
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
	has_many :orders

	validates :name, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_one :confirmation
	belongs_to :brand
	belongs_to :delivery
	belongs_to :state
	belongs_to :customer

	def self.update_state(order)	
		case order.state
			when order.state == State.pending
				order.state = State.confirmed
			when order.state == State.confirmed
				order.state = State.assigned
			when order.state == State.assigned
				order.state = State.in_transit
			else
				order.state = State.delivered
		end
	end
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :orders

	def self.pending
		State.find_by(state: "pending")
	end

	def self.confirmed
		State.find_by(state: "confirmed")
	end

	def self.assigned
		State.find_by(state: "assigned")
	end

	def self.in_transit
		State.find_by(state: "in_transit")
	end

	def self.delivered
		State.find_by(state: "delivered")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def new
  	@confirmation = Confirmation.new
  end

  def create
    @confirmation = Confirmation.find_by(otp: params[:confirmation][:otp])
    if @confirmation
      @confirmation.update_attributes(confirmation_params.merge(confirmed: true))
      @confirmation.order.update_attributes(confirmation_id: @confirmation.id, state: State.confirmed)
      redirect_to order_summary_path(@confirmation.order.id)
    elsif !@confirmation
      @confirmation = Confirmation.new(confirmation_params.merge(confirmed: false, otp: Confirmation.one_time_password))
      if @confirmation.save
        flash[:success] = "Your order reference number is: #{@confirmation.otp}"
        redirect_to root_path 
      else
        flash.now[:error] = "Phone number can't be blank"
        render action: :new
      end
    else
      flash.now[:error] = "contact your administrator"
    end       
  end

  def update
    @confirmation = Confirmation.find(params[:id])
    if @confirmation.update_attributes(confirmation_params)
      redirect_to @confirmation
    end
  end

  private

  def confirmation_params
  	params.require(:confirmation).permit(:phone_number, :customer_id, :order_id)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
  	@customer = Customer.new
  end

  def create
  	@customer = Customer.new(customer_params)
    if @customer.save
      session[:customer_id] = @customer.id
      current_order.update_attribute(:customer_id, @customer.id)
      redirect_to new_confirmation_path
    end
  end

  private

  def customer_params
  	params.require(:customer).permit(:delivery_address, :email, :name, :postcode)
  end
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  def login
  end

  def orders
    @orders = Order.all
  end

  def create
  	@delivery = Delivery.find_or_initialize_by(delivery_params)
    if @delivery.save
      log_in @delivery
      redirect_to delivery_orders_path(@delivery)
    else
      flash.now[:error] = "contact your administrator"
      render action: :login
    end
  end

  def show
    @delivery = Delivery.find(params[:id])
  end

  def destroy
    log_out
    redirect_to root_path
  end

  private

  def delivery_params
    params.require(:deliveries).permit(:name, :phone_number)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@order = Order.new
  	@confirmation = Confirmation.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def summary
    @order = Order.find(params[:order_id])
  end

  def create
  	@order = Order.new(order_params.merge(state: State.pending))
  	if @order.save
  		new_order @order
      redirect_to new_customer_path
  	else
  		redirect_to root_path
  	end
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update_attributes(order_params)
      flash[:notice] = "Order has been updated!"
      if @order.state == State.assigned
        redirect_to delivery_path(current_delivery)
      else
        redirect_to :back
      end
    else
      flash[:error] = "Something went wrong"
      redirect_to :back
    end
  end

  private

  def order_params
  	params.require(:order).permit(:weight_in_kg,
      :quantity,
      :preffered_time,
      :notes,
      :payment_amount_in_cents,
      :brand_id,
      :state_id,
      :delivery_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	private

  def log_in(delivery)
  	session[:delivery_id] = delivery.id
  end

  def current_delivery
  	@current_delivery ||= Delivery.find_by(id: session[:delivery_id])
  end

  def logged_in?
    !current_delivery.nil?
  end

  def log_out
    session.delete(:delivery_id)
    @current_delivery = nil
  end

  def new_order(order)
  	session[:order_id] = order.id
  end

  def current_order
  	@current_order ||= Order.find_by(id: session[:order_id])
  end
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/new.html.erb
<h4>Order successfully created! Now tell us where to send it.</h4>
<%= simple_form_for @customer do |f| %>	
	<%= f.hidden_field :order_id, value: session[:order_id] %>
	<%= f.input :name %>
	<%= f.input :email %>
	<%= f.input :delivery_address %>
	<%= f.input :postcode %>
	<%= f.submit 'Next', class: "btn btn-primary" %>
<% end %>

app/views/deliveries/login.html.erb
<%= simple_form_for(:deliveries, url: deliveries_path) do |f| %>
	<%= f.input :phone_number %>
	<%= f.submit 'login', class: "btn btn-primary" %>
<% end %>

app/views/deliveries/orders.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>Customer's name</th>
			<th>Address</th>
			<th>Postcode</th>
			<th>ETD</th>
			<th>KG's p/item</th>
			<th>Quantity</th>
			<th>Status</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @orders.each_with_index do |order, index| %>
			<tr>
				<td><%= index + 1 %></td>
				<td><%= order.customer.name %></td>
				<td><%= order.customer.delivery_address %></td>
				<td><%= order.customer.postcode %></td>
				<td><%= order.preffered_time.strftime("%H:%M") %></td>
				<td><%= order.weight_in_kg %></td>
				<td><%= order.quantity %></td>
				<% case order.state
						when State.pending %>
						<td>Not confirmed yet</td>
						<td><button class="btn btn-danger btn-sm" disabled="disabled">Awaiting confirmation</button></td>
					<% when State.confirmed %>
						<td>Confirmed </td>
						<td>
						<%= form_for(order, method: :patch) do |f| %>
							<%= f.hidden_field :delivery_id, value: current_delivery.id %>
							<%= f.hidden_field :state_id, value: order.state_id + 1 %>
							<%= f.submit 'Asign to me', class: "btn btn-default btn-sm" %>
						<% end %>
						</td>
					<% when State.assigned %>
						<td>Assigned to <%= order.delivery.name %></td>
						<td>
						<%= form_for(order, method: :patch) do |f| %>
							<%= f.hidden_field :state_id, value: order.state_id + 1 %>
							<%= f.submit 'Awaiting transfer', class: "btn btn-primary btn-sm", disabled: true %>
						<% end %>
						</td>
					<% when State.in_transit %>
						<td>In transit by <%= order.delivery.name %></td>
						<td><button class="btn btn btn-warning btn-sm" disabled="disabled">In Transit</button></td>
					<% else %>
						<td>Delivered by <%= order.delivery.name %> on <%= order.updated_at.strftime("%d/%m/%Y") %> at <%= order.updated_at.strftime("%H:%M") %></td>
						<td><button class="btn btn btn-success btn-sm" disabled="disabled">Delivered</button></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/deliveries/show.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Customer's name</th>
			<th>Address</th>
			<th>Postcode</th>
			<th>ETD</th>
			<th>KG's per item</th>
			<th>Quantity</th>
			<th>Reference No.</th>
			<th>Notes</th>
			<th>Status</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @delivery.orders.each do |order| %>
			<tr>
				<td><%= order.customer.name %></td>
				<td><%= order.customer.delivery_address %></td>
				<td><%= order.customer.postcode %></td>
				<td><%= order.preffered_time.strftime("%H:%M") %></td>
				<td><%= order.weight_in_kg %></td>
				<td><%= order.quantity %></td>
				<td><%= order.confirmation.otp %></td>
				<td><%= order.notes %></td>
				<% if order.state == State.assigned %>
						<td>Assigned</td>
						<td>
						<%= form_for(order, method: :patch) do |f| %>
							<%= f.hidden_field :state_id, value: order.state_id + 1 %>
							<%= f.submit 'Transfer', class: "btn btn-default btn-sm" %>
						<% end %>
						</td>
					<% elsif order.state == State.in_transit %>
						<td>In transit</td>
						<td>
						<%= form_for(order, method: :patch) do |f| %>
							<%= f.hidden_field :state_id, value: order.state_id + 1 %>
							<%= f.submit 'Deliver', class: "btn btn-default btn-sm" %>
						<% end %>
						</td>
					<% else %>
						<td>Delivered</td>
						<td></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/home/index.html.erb
<%= render partial: 'confirmations/confirm' %>
<hr>
<h1>Welcome to Get...!</h1>
<h3>Your one stop solution for all your ... needs.</h3>
<%= render partial: 'orders/new' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GainPropane</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
	<body>
		<nav class="navbar navbar-inverse navbar-static-top">
	    <div class="container">
	      <div class="navbar-header">
	        <a class="navbar-brand" >Ordering</a>
	      </div>
	      <ul class="nav navbar-nav">
	        <% if logged_in? %>
	        	<li <% if params[:controller] == "deliveries" && params[:action] == "show" %> class="active"<% end %>><a href="<%= delivery_path(current_delivery) %>">My Deliveries</a></li>
	        	<li <% if params[:controller] == "deliveries" && params[:action] == "orders" %> class="active"<% end %>><a href="<%= delivery_orders_path(current_delivery) %>">Orders</a></li>
	        	<li><%= link_to 'Logout', delivery_path(current_delivery), method: 'delete' %></li>
	        <% else %>
	        	<li <% if params[:controller] == "home" && params[:action] == "index" %> class="active"<% end %>><a href="<%= root_path %>">Home</a></li>
	        	<li <% if params[:controller] == "deliveries" && params[:action] == "login" %> class="active"<% end %>><a href="<%= login_deliveries_path %>">Login</a></li>
	        <% end %>
	      </ul>
	    </div>
	  </nav>
	  <div class="container">
			<% flash.each do |message_type, message| %>
				<p><strong><%= message %></strong></p>
			<% end %>
			<%= yield %>
			<% #= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/orders/_new.html.erb
<%= simple_form_for @order do |f| %>	
	<%= f.association :brand, prompt: '--select--' %>
	<%= f.input :weight_in_kg, collection: ['12', '14'], prompt: '--select--' %>
	<%= f.input :quantity, collection: ['1', '2', '3', '4', '5'], prompt: '--select--' %>
	<%= f.input :preffered_time, :as => :time, :minute_step => 15 %>
	<%= f.input :notes %>
	<%= f.submit 'Next', class: 'btn btn-primary' %>	
<% end %>

app/views/orders/show.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Customer's name</th>
			<th>Address</th>
			<th>Postcode</th>
			<th>ETD</th>
			<th>KG's per item</th>
			<th>Quantity</th>
			<th>Reference No.</th>
			<th>Status</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @order.customer.name %></td>
			<td><%= @order.customer.delivery_address %></td>
			<td><%= @order.customer.postcode %></td>
			<td><%= @order.preffered_time.strftime("%H:%M") %></td>
			<td><%= @order.weight_in_kg %></td>
			<td><%= @order.quantity %></td>
			<td><%= @order.confirmation.otp %></td>
			<% if @order.state == State.assigned %>
					<td>Assigned</td>
					<td>
					<%= form_for(@order, method: :patch) do |f| %>
						<%= f.hidden_field :state_id, value: @order.state_id + 1 %>
						<%= f.submit 'Transfer', class: "btn btn-default btn-sm" %>
					<% end %>
					</td>
				<% else %>
					<td>In transit</td>
					<td>
					<%= form_for(@order, method: :patch) do |f| %>
						<%= f.hidden_field :state_id, value: @order.state_id + 1 %>
						<%= f.submit 'Deliver', class: "btn btn-default btn-sm" %>
					<% end %>
					</td>
			<% end %>
		</tr>
	</tbody>
</table>

app/views/orders/summary.html.erb
<table class="table table-striped">
	<tr><th>Customer's name</th><td><%= @order.customer.name %></td></tr>
	<tr><th>Address</th><td><%= @order.customer.delivery_address %></td></tr>
	<tr><th>Postcode</th><td><%= @order.customer.postcode %></td></tr>
	<tr><th>ETD</th><td><%= @order.preffered_time.strftime("%H:%M") %></td></tr>
	<tr><th>KG's per item</th><td><%= @order.weight_in_kg %></td></tr>
	<tr><th>Quantity</th><td><%= @order.quantity %></td></tr>
	<tr><th>Reference No.</th><td><%= @order.confirmation.otp %></td></tr>	
	<tr><th>Status</th>
		<% case @order.state
			when State.confirmed %>
				<td>Confirmed</td> 
			<% when State.assigned %>
				<td>Assigned</td>
			<% when State.in_transit %>
				<td>In transit</td>					
			<% else %>
			<td>Delivered</td>
		<% end %>
	</tr>
</table>